apiVersion: v1
kind: Secret
metadata:
  labels:
    service: jwtsecret
  namespace: {{.Release.Namespace}}
  name: jwtsecret
type: Opaque
data:
  default: {{.Values.secret.jwtSecret | b64enc}}

---

apiVersion: v1
kind: Secret
metadata:
  labels:
    service: guardian-prover-private-key
  namespace: {{.Release.Namespace}}
  name: guardian-prover-private-key
type: Opaque
data:
  default: {{.Values.secret.guardianProverPrivateKey | b64enc}}

