apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiko-geth.fullname" . }}
  labels:
    {{- include "taiko-geth.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "taiko-geth.selectorLabels" . | nindent 4 }}
  ports:
    - name: ws
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: http
      protocol: TCP
      port: 8551
      targetPort: 8551
