apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "taiko-geth.fullname" . }}
  labels:
    {{- include "taiko-geth.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  serviceName: taiko-geth
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: taiko-geth
  volumeClaimTemplates:
  - metadata:
      name: taiko-data
    spec:
      storageClassName: {{ .Values.global.storage.className }}
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.global.storage.request }}
  template:
    metadata:
      labels:
        app: taiko-geth
    spec:
      volumes:
      - name: jwtsecret
        secret:
          secretName: jwtsecret
      containers:
      #### Taiko node
      - name: taiko
        image: "us-docker.pkg.dev/evmchain/{{ with (index .Values .Values.global.network) }}{{ .image.repo }}/taiko-geth:{{ .image.tag }}{{ end }}"
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          geth \
            --datadir=/taiko/data \
            --port=30303 \
            --http \
            --http.addr 0.0.0.0 \
            --http.port 8545 \
            --http.vhosts "*" \
            --http.corsdomain "*" \
            --http.api net,eth,web3,txpool,debug,taiko \
            --ws \
            --ws.addr 0.0.0.0 \
            --ws.port 8546 \
            --ws.origins "*" \
            --ws.api eth,net,web3,txpool,debug,taiko \
            --metrics \
            --metrics.port 6060 \
            --metrics.addr 0.0.0.0 \
            --cache 4096 \
            --maxpeers 50 \
            --syncmode snap \
            --gcmode archive \
            --snapshot \
            --log.rotate \
            --log.compress \
            --log.maxsize 10 \
            --log.maxage 10 \
            --log.format logfmt \
            --authrpc.addr 0.0.0.0 \
            --authrpc.port 8551 \
            --authrpc.jwtsecret /jwtsecret/default \
            --authrpc.vhosts "*" \
            --discv5 \
            --allow-insecure-unlock \
            --networkid={{ (index .Values .Values.global.network).id }} \
            --nat "extip:$(POD_IP)" \
            --bootnodes "{{ (index .Values .Values.global.network).bootnodes }}" \
            --taiko 2>&1
        ports:
          - containerPort: 8545
          - containerPort: 8546
          - containerPort: 8551
          - containerPort: 6060
          - containerPort: 30303
          - containerPort: 30303
            protocol: UDP
        volumeMounts:
          - name: taiko-data
            mountPath: /taiko/data
          - name: jwtsecret
            mountPath: /jwtsecret
            readOnly: true
        resources:
          requests:
            cpu: {{ .Values.global.resources.requests.cpu }}
            memory: {{ .Values.global.resources.requests.memory }}
          limits:
            cpu: {{ .Values.global.resources.limits.cpu }}
            memory: {{ .Values.global.resources.limits.memory }}
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /
            port: 8545
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
          exec:
            command:
            - /bin/sh
            - -c
            - "geth attach --datadir=/taiko/data --exec 'eth && !eth.syncing' | grep true"
