global:
  network: hekla

taiko-client:
  global:
    network: "{{ .Values.global.network }}"
    mode: driver
    endpoints:
      l1Http: "http://ethereum-node-holesky-execution:8545"
      l1Ws: "ws://ethereum-node-holesky-execution:8545"
      l1Beacon: "http://ethereum-node-holesky-beacon:5052"

taiko-geth:
  global:
    network: "{{ .Values.global.network }}"
