global:
  network: hekla

taiko-client:
  global:
    network: "{{ .Values.global.network }}"
    mode: driver

taiko-geth:
  global:
    network: "{{ .Values.global.network }}"

ethereum-node:
  enabled: true
  geth:
    enabled: true
  lighthouse:
    enabled: true
  global:
    main:
      network: holesky
