apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taiko-client.fullname" . }}
  labels:
    {{- include "taiko-client.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "taiko-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taiko-client.labels" . | nindent 8 }}
    spec:
      volumes:
      - name: jwtsecret
        secret:
          secretName: {{ include "taiko-client.fullname" . }}-jwt
      {{- if eq .Values.global.mode "proposer" }}
      env:
        - name: PROPOSER_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "taiko-client.fullname" . }}-proposer-private-key
              key: default
      {{- end }}
      {{- if or (eq .Values.global.mode "prover") (eq .Values.global.mode "guardian") }}
      env:
        - name: PROVER_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "taiko-client.fullname" . }}-prover-private-key
              key: default
      {{- end }}
      containers:
      - name: {{ printf "taiko-client-%s" .Values.global.mode }}
        image: "{{ with (index .Values .Values.global.network) }}{{ .image.repo }}:{{ .image.tag }}{{ end }}"
        volumeMounts:
          - name: jwtsecret
            mountPath: /jwtsecret
            readOnly: true
        args:
          # Args for specific mode
          {{- range $arg := (index .Values .Values.global.mode).args }}
          - {{ tpl $arg $ }}
          {{- end }}
          # Default args
          {{- range $arg := .Values.global.defaultClientArgs }}
          - {{ tpl $arg $ }}
          {{- end }}
        resources:
          requests:
            cpu: {{ .Values.global.resources.requests.cpu }}
            memory: {{ .Values.global.resources.requests.memory }}
          limits:
            cpu: {{ .Values.global.resources.limits.cpu }}
            memory: {{ .Values.global.resources.limits.memory }}
