apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "taiko-client.fullname" . }}
  labels:
    {{- include "taiko-client.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  serviceName: taiko-client
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "taiko-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taiko-client.labels" . | nindent 8 }}
    spec:
      volumes:
      - name: jwtsecret
        secret:
          secretName: {{ include "taiko-client.fullname" . }}-jwt
      containers:
      - name: {{ printf "taiko-client-%s" .Values.global.mode }}
        image: "us-docker.pkg.dev/evmchain/{{ with (index .Values .Values.global.network) }}{{ .image.repo }}/taiko-client:{{ .image.tag }}{{ end }}"
        volumeMounts:
          - name: jwtsecret
            mountPath: /jwtsecret
            readOnly: true
        args:
          # Args for specific mode
          {{- range $arg := (index .Values .Values.global.mode).args }}
          - {{ tpl $arg $ }}
          {{- end }}
          # Default args
          {{- range $arg := .Values.global.defaultClientArgs }}
          - {{ tpl $arg $ }}
          {{- end }}
        {{- if eq .Values.global.mode "guardian" }}
        env:
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: guardian-prover-private-key
                key: default
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.global.resources.requests.cpu }}
            memory: {{ .Values.global.resources.requests.memory }}
          limits:
            cpu: {{ .Values.global.resources.limits.cpu }}
            memory: {{ .Values.global.resources.limits.memory }}
